
// This file was auto-generated by ML.NET Model Builder. 

using IrisFlowerML_ConsoleApp;

// Create single instance of sample data from first line of dataset for model input
IrisFlowerML.ModelInput sampleData = new IrisFlowerML.ModelInput()
{
    Col0 = 4.9F,
    Col1 = 3F,
    Col2 = 1.4F,
    Col3 = 0.2F,
};

// Make a single prediction on the sample data and print results
var predictionResult = IrisFlowerML.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Col4 with predicted Col4 from sample data...\n\n");


Console.WriteLine($"Col0: {4.9F}");
Console.WriteLine($"Col1: {3F}");
Console.WriteLine($"Col2: {1.4F}");
Console.WriteLine($"Col3: {0.2F}");
Console.WriteLine($"Col4: {@"Iris-setosa"}");


Console.WriteLine($"\n\nPredicted Col4: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

